### ISSUE TITLE
Reach UX QA

### ISSUE THREAD

**Issue by j-jaworski** [wellcometrust/reach#443]
Ahead of iterating on the Alpha design I have done a quick design QA of the live product.

Design QA's are notoriously tricky to capture, I am using an approach that has worked well in other teams, but please let me know if there is a preference to how these should be communicated.

For each page I have annotated a screenshot, and listed the annotations below as a checklist. Some of the notes might seem a little vague, this is because I don't want to be too restrictive and annoying about how to implement the designs.

If you have any suggestions that might improve on this process, or questions about any of the points raised, just shout. 

### Reach Homepage
![Reach_QA_Home.png](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/38068e45-cbc5-4141-94f2-2e13654809fe)

- [x] 01 Make spacing consistent 64px
- [x] 02 Arrow and image of results should always anchor to the bottom of the window
- [x] 03 Increase space
- [x] 04 Bold headings style 
- [x] 05 Make space before button consistent
- [x] 06 Footer should be closer to the bottom of the page across all pages
- [x] 07 Anchor link should be ‘scroll-behavior: smooth`

### Discover Citations
![Reach_QA_Discover-citations.png](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/bd2f8a5b-988a-4508-974d-b9d46d61b816)

_These amends should also be applied to  reach/browse-policy-documents_

- [x] 01 Reduce this space we should aim to make the input field positioned centrally in window
- [x] 02 Make this wider, so that the text is only on two lines
- [x] 03 Make this wider, so that the text is only on two lines
- [x] 04 Make this `14px #292929`
- [x] 05 Increase padding either side of text within button
- [x] 06 Footer should be closer to the bottom of the page across all pages

### Citation Results
![Reach_QA_Citations-results.png](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/7bfdd9c6-312c-419f-9d9a-82e95b880b3b)
- [x] 01 Link back to `discover citaions`
- [x] 02 Add non-cliclable breadcrumb “results”
- [x] 03 Width of descriptive text should span same as the input field
- [x] 04 Button should have a height of 44px
- [x] 05 Search input and button shoulf have a height of 44px
- [x] 06 Should read “1 to 26 of 229 results”
- [x] 07 Prev should be hidden on first page of results
- [x] 08 Include hover states for links
- [x] 09 Column headers should be  `font-size: 11px; color: #292929;`
- [x] 10 Column headers should be aligned to the middle of the row
- [x] 11 Include states for sorting arrows to feedback to the user when something has been applied
- [x] 12 Add more padding aropund icon
- [x] 13 Make column header row background #F2F2F2
- [x] 14 Truncate to the width of the column
- [x] 15 Cell text should be; `font-size: 14px; color: #292929;`
_This should reduce the number of hight rows in the table. We should also consider truncating Journal title and authors too unsure that we have greater constistency in height of rows._
- [x] 16 On hover cursor should change to indicate that it is interactive
- [x] 17 Remove mysterious 1px line
- [x] 18 Add icon to indicate that the link opens in a new window
- [x] 19 Make padding either side of > icon the same
- [x] 20 Remove coloured background on results pages
- [x] 21 Info boxes should span same width as results table
- [x] 22 Branding and links should be have bottom- margin of only 40px to the end of the page
- [x] 23 Include summary sentance “Searching for “Malaria” in over 1.1 million research publications that have been cited in policy documents.”

### Policy Documents results
![Reach_QA_Policy-documents-results.png](https://images.zenhubusercontent.com/5bcdab41ba9b001064ad8afc/a9eb0014-70c5-470a-8847-af2bc2870941)
- [x] 01 Link back to `browse policy documents`
- [x] 02 Add non-cliclable breadcrumb “ > results”
- [x] 03 Should read “1 to 26 of 229 results
- [x] 04 Include summary sentance “Searching for “Vaccines” in PDFs from the websites of UNICEF, Médecins Sans Frontières, National Insititute for Clinical Excellence, the World Health Organisation, UK Government  and UK Parliament.”
- [x] 05 Button should have a height of 44px
- [x] 06 Search input and button shoulf have a height of 44px
- [x] 07 Prev should be hidden on first page of results
- [x] 08 Include hover states for links 
- [x] 09 Include background cell colour
- [x] 10 Increase width of Policy document column, this column can be probably 60% width of the whole table
- [x] 11 Column headers should be  `font-size: 11px; color: #292929;`
- [x] 12 Sort icons should be aligned to the middle of the row
- [x] 13 Include states for sorting arrows to feedback to the user when something has been applied
- [x] 14 Add more padding between header and icon
- [x] 15 Make column header row background #F2F2F2
- [x] 16 Increase padding on left of first column
- [x] 17 Add icon to indicate that the link opens in a new window
- [x] 18 Remove coloured background on results pages

**Comment by kristinenielsen** [comment]
Hold off on this until we have the new UI in place for the tables improvement

**Comment by j-jaworski** [comment]
The majority of the issues highlighted with the tables should be made obsolete by the latest designs

All available on Zeplin
https://app.zeplin.io/project/58bd9edd507012294c189959/dashboard?seid=5e592d74b54d1b673f400e5e

**Comment by SamDepardieu** [comment]
@j-jaworski About Citation results nº6/Policy docs results nº6:
Zeplin mockup read `Showing 1 - 25 of 42 results` but here it says `1 to 26 of 229 results`. Which one should I use?

**Comment by j-jaworski** [comment]
@SamDepardieu 25 results per page makes more sense – probably the other option was a typo

**Comment by SamDepardieu** [comment]
@j-jaworski Cool, last things:
>  Prev should be hidden on first page of results
This is not hidden but `disabled` on mockups, I guess the disabled state is the one to use?

> Make column header row background #F2F2F2
This is `#FFFFFF` on mockups, it looks right to me, but should I use `#f2f2f2` instead?

> Column headers should be aligned to the middle of the row
This is aligned: left on mockups

I've done everything according to mockups, but I'd rather check now which version is alright :)

**Comment by j-jaworski** [comment]
1. use disabled state
2. keep as FFFFFF
3. I think this was about them being centred vertically within the row, rather than the font being left/right/centred aligned – might have been specifically about the icons as well – they didn't look visually centred in that version

**Comment by SamDepardieu** [comment]
Perfect then, this is done 👌
