### ISSUE TITLE
Reach  - Iterate on tables 

### ISSUE THREAD

**Issue by j-jaworski** [wellcometrust/reach#444]
### Things to consider

_Some of these items should be split into their own tickets_

- [x]  Expandable rows, fix headers and copy #461
- [x] Zebra rows #457
- [x] Sort icons <> add states #458
- [x] New window icon #455
- [x] Filters, including date range, search by "author" #459
- [ ] Advanced search (considered as part of #452 - needs further exploration)
- [x]  Sub-search #459
- [x] Add Favicon for Reach #451
- [x] System feedback when tables loading and sorting #454
- [x] More guidance before search, and when showing results (content) → added "i. Learn more about these results" link that should go to a page that provides more detail about why these results are served. Reason being that not all users will need this extra context all the time. Once they have learnt it will be redundant in the interface.
- [x] Include DOI and meta data as per #440
- [ ] Mock designs for one search bar two CTA buttons #452
- [ ] Check boxes and custom built csv export #453
- [ ] Pop-up Modal with more info and linking #460
- [x]  Basic page for things like contact us #456
- [ ] Add ... Action icon on results for users to flag false positives etc #453

**Comment by kristinenielsen** [comment]
@j-jaworski can you please update status on this?

**Comment by j-jaworski** [comment]
Closing as everything is split out into separate tickets now
