### ISSUE TITLE
Create weekly alerts for times when database and S3 fail certain tests

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reach#96]
Tests might include:

- [ ] Are there any deletions from S3? (e.g. https://github.com/wellcometrust/policytool/issues/47)
- [ ] Are there duplicate documents with different (or the same) file hashes? (e.g. https://github.com/wellcometrust/policytool/issues/48)
- [ ] Do S3 and the database have the same numbers of results (e.g. https://github.com/wellcometrust/policytool/issues/57)
- [ ] Each week the number of policy documents does not decrease
- [ ] Each week the number of references found in policy documents does not decrease

**Comment by nsorros** [comment]
That would be very helpful. Looking forward to hearing what @SamDepardieu and @hblanks think.

**Comment by SamDepardieu** [comment]
Would be good to have them.
1) requires us to have an history of the files we have on S3, implying some kind of persistent DB probably.
2) Might be difficult to know if a file with a different hash is a duplicate (the title can be different, the slightliest change to the file content changes the hash a lot, lack of other informations...) but we can surely get rid of some of them by at least checking the titles.
3) This one can be done easily I think
4) I don't know how it could decrease, but fair enought, it's not too hard to test. Same as 1), though, we need a persisting history. If you're talking about the DB though, I can assure you that it won't decrease, as we never drop anything.
5) Same as 4.

**Comment by jdu** [comment]
The feedback described may mostly be mitigated by getting #400 and #419 in place as we'll be able to view and set alerts on metrics like these through Grafana / Prometheus.
